services:
  wrapper:
    container_name: wrapper
    image: ghcr.io/chas0000/amdl_wrapper:latest  #或chaslllll/amdl_wrapper:latest
    network_mode: host
    #ports:
    #   - "8880:8080"     # 如果不使用 host 模式，可以使用端口映射 8080是管理端口，还要放行实例端口如10200、20200
    volumes:
      - ./instances/:/app/wrapper/instances  #各区wrapper保存位置
      - ./config/:/app/config/  
  amdl_m:
    container_name: amdl
    image: ghcr.io/chas0000/amdl_m:latest #或chaslllll/amdl_m:latest
    network_mode: host
    environment:
      TTYD_USER: ""                  #TTYD的用户名和密码，两者都设定时才起效，否则为无鉴权模式
      TTYD_PASS: ""
      SSH_USER: "root"               #SSH登录用户名（默认：root，与ttyd同权限）
      SSH_PASSWORD: "password"       #SSH登录密码（默认：password）
      SSH_PORT: "2122"               #SSH端口（默认：22，host模式下可修改避免冲突）
    # 如果不使用 host 模式，可以使用端口映射
    #network_mode: bridge
    #ports:
    #   - "7681:7681"
    #   - "2122:22"
    volumes:
      - /mnt/disk1:/mnt/disk1        #映射需要保持音乐的目录，后半段需与config.toml中一致，自己修改
      - ./config/:/app/config/      #amdl的config存放位置，第一次运行时会自动拷贝备份
      #- ./start.sh:/app2/start.sh
