name: 发布容器

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download MP4Box-output
      uses: actions/download-artifact@v4
      with:
        name: MP4Box-output
        
    - name: Download amdl-output
      uses: actions/download-artifact@v4
      with:
        name: amdl-output
    - name: Move files    
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/backup
        mv ${GITHUB_WORKSPACE}/amdl-output/z_amdl/config ${GITHUB_WORKSPACE}/backup/
        mv ${GITHUB_WORKSPACE}/amdl-output/s_amdl/config ${GITHUB_WORKSPACE}/backup/
        

    - name: Set up QEMU
      # QEMU 是用于在一种架构上模拟另一种架构的工具  
      # Docker BuildKit 使用 QEMU 来实现跨平台构建  
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 设置环境变量以包含时间戳  
    - name: Get current date
      run: export TZ='Asia/Shanghai'&& echo "BUILD_DATE=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    # 构建并推送 Docker 镜像  
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/amdl-docker:latest
          ${{ secrets.DOCKER_USERNAME }}/amdl-docker:${{ env.BUILD_DATE }}
          ghcr.io/${{ github.repository_owner }}/amdl-docker:latest
          ghcr.io/${{ github.repository_owner }}/amdl-docker:${{ env.BUILD_DATE }}
  
