name: 发布容器

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl git make build-essential bash zlib1g-dev ca-certificates
        wget https://golang.org/dl/go1.23.9.linux-amd64.tar.gz
        sudo tar -C /usr/local -xvzf go1.23.9.linux-amd64.tar.gz
        echo "export PATH=\$PATH:/usr/local/go/bin" >> ~/.bashrc
        source ~/.bashrc
        go version

    - name: Build apple-music-downloader (zhaarey)
      run: |
        git clone https://github.com/zhaarey/apple-music-downloader.git
        cd ${GITHUB_WORKSPACE}/apple-music-downloader
        
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o dl main.go
        mkdir -p ${GITHUB_WORKSPACE}/output
        mv dl ${GITHUB_WORKSPACE}/output/
        mv config.yaml ${GITHUB_WORKSPACE}/output/

    - name: Build apple-music-downloader (sky8282)
      run: |
        mkdir -p ./sky
        cd ${GITHUB_WORKSPACE}/sky
        git clone https://github.com/sky8282/apple-music-downloader.git
        cd ${GITHUB_WORKSPACE}/sky/apple-music-downloader
        sed -i 's|config.yaml|sky_config.yaml|g' ./main.go
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o sdl main.go
        mkdir -p ${GITHUB_WORKSPACE}/output/
        mv sdl ${GITHUB_WORKSPACE}/output/
        cp config.yaml ${GITHUB_WORKSPACE}/output/sky_config.yaml

    - name: Download ttyd
      run: |
        wget $(curl -s https://api.github.com/repos/tsl0922/ttyd/releases/latest | grep browser_download_url | grep 'ttyd.x86_64' | cut -d '\"' -f 4)
        mv ttyd.x86_64 ${GITHUB_WORKSPACE}/output/ttyd
        chmod -R 777 ${GITHUB_WORKSPACE}/output

    - name: List output files
      run: |
        ls -lR ${GITHUB_WORKSPACE}/output

    - name: Upload AMDL artifacts
      uses: actions/upload-artifact@v4
      with:
        name: amdl-output
        path: |
          ${{ github.workspace }}/output

    - name: git_MP4box
      run: |
        apt update && apt install build-essential pkg-config g++ git cmake yasm zlib1g-dev -y
        git clone https://github.com/gpac/gpac.git gpac_public
        cd gpac_public
        ./configure --static-bin
        make
        ls -l ./bin/gcc
        mv ./bin/gcc/MP4Box ${GITHUB_WORKSPACE}
        ls -l ${GITHUB_WORKSPACE}

    - name: Upload Go build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MP4Box-output
        path: |
          ${{ github.workspace }}/MP4Box

    - name: Move files    
      run: |
        ls -lR ${GITHUB_WORKSPACE}/output
        mkdir -p ${GITHUB_WORKSPACE}/backup/
        mv ${GITHUB_WORKSPACE}/output/config.yaml ${GITHUB_WORKSPACE}/backup/config.yaml
        mv ${GITHUB_WORKSPACE}/output/sky_config.yaml ${GITHUB_WORKSPACE}/backup/sky_config.yaml
        ls -l ${GITHUB_WORKSPACE}/backup
        

    - name: Set up QEMU
      # QEMU 是用于在一种架构上模拟另一种架构的工具  
      # Docker BuildKit 使用 QEMU 来实现跨平台构建  
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 设置环境变量以包含时间戳  
    - name: Get current date
      run: export TZ='Asia/Shanghai'&& echo "BUILD_DATE=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    # 构建并推送 Docker 镜像  
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/amdl-docker:latest
          ${{ secrets.DOCKER_USERNAME }}/amdl-docker:${{ env.BUILD_DATE }}
          ghcr.io/${{ github.repository_owner }}/amdl-docker:latest
          ghcr.io/${{ github.repository_owner }}/amdl-docker:${{ env.BUILD_DATE }}
  
