name: 预编译MP4box

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: git_MP4box
      run: |
        apt update && apt install build-essential pkg-config g++ git cmake yasm zlib1g-dev -y
        git clone https://github.com/gpac/gpac.git gpac_public
        cd gpac_public
        ./configure --static-bin
        make
        ls -l ./bin/gcc
        mv ./bin/gcc/MP4Box ${GITHUB_WORKSPACE}
        ls -l ${GITHUB_WORKSPACE}

    - name: Upload Go build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MP4Box-output
        path: |
          ${{ github.workspace }}/MP4Box
    - name: GH Release Action
      uses: softprops/action-gh-release@v1
      with:
        major: 1  # 主版本号
        minor: 0  # 次版本号
        github-token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token 进行认证
        files: ${{ github.workspace }}/MP4Box
