name: 预编译MP4box

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: git_MP4box
      run: |
        apt update && apt install build-essential pkg-config g++ git cmake yasm zlib1g-dev -y
        git clone https://github.com/gpac/gpac.git gpac_public
        cd gpac_public
        ./configure --static-bin
        make
        ls -l ./bin/gcc
        mv ./bin/gcc/MP4Box ${GITHUB_WORKSPACE}
        ls -l ${GITHUB_WORKSPACE}

    - name: Upload Go build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MP4Box-output
        path: |
          ${{ github.workspace }}/MP4Box
    - name: Create a tag
      run: |
          TAG_NAME="MP4Box-v1.0.${{ github.run_id }}"  # 使用 run_id 或其他方式自动生成版本号
          git tag $TAG_NAME
          git remote set-url origin https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin $TAG_NAME  # 推送标签到 GitHub

      # 发布构建产物到 GitHub Release
    - name: Create GitHub Release and Upload Artifacts
      uses: softprops/action-gh-release@v1
      with:
        tag: ${{ steps.create_tag.outputs.tag_name }}  # 使用创建的标签
        files: ${{ github.workspace }}/MP4Box  
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # 使用自定义的 GitHub Token 进行认证
