name: 预编译amdl

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build inside Alpine container
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace alpine:latest sh -c "
          apk update && apk add --no-cache \
            git \
            go \
            make \
            build-base \
            wget \
            curl \
            bash \
            zlib-dev \
            ca-certificates && \
          cd /workspace  &&\
          git clone https://github.com/zhaarey/apple-music-downloader.git &&  \
          cd /workspace/apple-music-downloader &&  \
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dl main.go && \
          mkdir -p /workspace/output/z_amdl &&  \
          chmod -R 777 /workspace/output && \
          mv /workspace/apple-music-downloader/dl /workspace/output/z_amdl && \
          mv /workspace/apple-music-downloader/config.yaml /workspace/output/z_amdl && \
          cd /workspace  &&\
          wget \$(curl -s https://api.github.com/repos/tsl0922/ttyd/releases/latest | grep browser_download_url | grep 'ttyd.x86_64' | cut -d '\"' -f 4) && \
          mv ttyd.x86_64 /workspace/output/ttyd && \
          ls -l /workspace/output"
    - name: git_MP4box
      run: |
        apt update && apt install build-essential pkg-config g++ git cmake yasm zlib1g-dev -y
        git clone https://github.com/gpac/gpac.git gpac_public
        cd gpac_public
        ./configure --static-bin
        make
        ls -l ./bin/gcc
        mv ./bin/gcc/MP4Box ${GITHUB_WORKSPACE}/output
        ls -l ${GITHUB_WORKSPACE}

    - name: Upload Go build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: go-build-artifacts
        path: |
          ${{ github.workspace }}/output


    - name: Create Release and Upload Artifacts
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ github.run_number }}"
        name: "Build Artifacts v${{ github.run_number }}"
        body: "Automatic build from GitHub Actions"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          z_amdl/**
          ttyd
          MP4Box
          wrapper/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
