name: 预编译amdl和ttyd

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build inside Alpine container
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace alpine:latest sh -c "
          apk update && apk add --no-cache \
            git \
            go \
            make \
            build-base \
            wget \
            curl \
            bash \
            zlib-dev \
            ca-certificates && \
          cd /workspace  &&\
          git clone https://github.com/zhaarey/apple-music-downloader.git &&  \
          cd /workspace/apple-music-downloader &&  \
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dl main.go && \
          mkdir -p /workspace/output/z_amdl &&  \
          mv /workspace/apple-music-downloader/dl /workspace/output/z_amdl && \
          mv /workspace/apple-music-downloader/config.yaml /workspace/output/z_amdl && \
          mkdir -p /workspace/sky &&\
          cd /workspace/sky  &&\
          mkdir 
          git clone https://github.com/sky8282/apple-music-downloader.git  &&  \
          cd /workspace/sky/apple-music-downloader &&  \
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o sdl main.go && \
          mkdir -p /workspace/output/s_amdl &&  \
          mv /workspace/sky/apple-music-downloader/sdl /workspace/output/s_amdl && \
          mv /workspace/sky/apple-music-downloader/config.yaml /workspace/output/s_amdl && \
          cd /workspace  &&\
          wget \$(curl -s https://api.github.com/repos/tsl0922/ttyd/releases/latest | grep browser_download_url | grep 'ttyd.x86_64' | cut -d '\"' -f 4) && \
          mv ttyd.x86_64 /workspace/output/ttyd && \
          ls -l /workspace/output"

    - name: Upload Go build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: amdl-output
        path: |
          ${{ github.workspace }}/output
    - name: Create a tag
      run: |
          TAG_NAME="AMDL-v1.0.${{ github.run_id }}"  # 使用 run_id 或其他方式自动生成版本号
          git tag $TAG_NAME
          git push origin $TAG_NAME  # 推送标签到 GitHub      
    - name: GH Release Action
      uses: softprops/action-gh-release@v1
      with:
        tag: ${{ steps.create_tag.outputs.tag_name }}  # 使用创建的标签
        files: ${{ github.workspace }}/output/* 
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
