name: 预编译amdl

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build inside Alpine container
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace alpine:latest sh -c "
          apk update && apk add --no-cache \
            git \
            go \
            make \
            build-base \
            wget \
            curl \
            bash \
            zlib-dev \
            ca-certificates && \
          cd /workspace  &&\
          git clone https://github.com/zhaarey/apple-music-downloader.git &&  \
          cd /workspace/apple-music-downloader &&  \
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dl main.go && \
          mkdir /workspace/z_amdl &&  \
          mv /workspace/apple-music-downloader/dl /workspace/z_amdl && \
          mv /workspace/apple-music-downloader/config.yaml /workspace/z_amdl && \
          ls -l /workspace/z_amdl"
        
    - name: Upload Go build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: go-build-artifacts
        path: |
          ${{ github.workspace }}/z_amdl
          
    - name: Create Release and Upload Artifacts
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ github.run_number }}"
        name: "Build Artifacts v${{ github.run_number }}"
        body: "Automatic build from GitHub Actions"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          z_amdl/**
          ttyd
          MP4Box
          wrapper/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
